/**
 * wallet.ts
 * ─────────
 * Derives the platform mint key wallet from MINT_KEY_MNEMONIC and exposes
 * the operations the watcher needs: balance check, send transfer.
 *
 * The wallet is V4 (the format Tonkeeper and most TON wallets generate
 * by default). If the user's mint key was generated by a wallet using a
 * different version, the derived address won't match what they funded
 * and the watcher will refuse to act until reconciled.
 */

import BN from "bn.js";
import {
  Address,
  Cell,
  CellMessage,
  CommonMessageInfo,
  InternalMessage,
  TonClient,
  WalletContract,
  WalletV4Source,
} from "ton";
import { KeyPair, mnemonicToWalletKey } from "ton-crypto";
import { getClient } from "./ion-rpc";

let cached: {
  contract: WalletContract;
  keyPair: KeyPair;
  address: Address;
} | null = null;

/**
 * Derive the platform mint key wallet from the MINT_KEY_MNEMONIC env var.
 * Cached after first call so we don't repeatedly run PBKDF2.
 */
export async function getMintKeyWallet(): Promise<{
  contract: WalletContract;
  keyPair: KeyPair;
  address: Address;
}> {
  if (cached) return cached;

  const mnemonic = (process.env.MINT_KEY_MNEMONIC ?? "").trim();
  if (!mnemonic) {
    throw new Error("MINT_KEY_MNEMONIC env var is not set");
  }
  const words = mnemonic.split(/\s+/).filter(Boolean);
  if (words.length !== 24) {
    throw new Error(
      `MINT_KEY_MNEMONIC must be 24 words separated by whitespace, got ${words.length}`,
    );
  }

  const keyPair = await mnemonicToWalletKey(words);
  const client = getClient();
  const source = WalletV4Source.create({
    publicKey: keyPair.publicKey,
    workchain: 0,
  });
  const contract = WalletContract.create(client, source);

  cached = { contract, keyPair, address: contract.address };
  return cached;
}

/**
 * Read the mint key wallet's current balance.
 * Returns BN nano-ION. 0 if the wallet hasn't been deployed yet
 * (i.e. has never received any ION).
 */
export async function getMintKeyBalance(): Promise<BN> {
  const { address } = await getMintKeyWallet();
  const client = getClient();
  try {
    const info = await client.getBalance(address);
    return info as BN;
  } catch {
    return new BN(0);
  }
}

/**
 * Build + sign + broadcast a mint message from the mint key wallet to the
 * collection contract. Returns the cell-hash of the transfer (used to track
 * the broadcast tx) and the seqno that was consumed.
 */
export async function sendMint(args: {
  collectionAddress: Address;
  mintBody: Cell;
  /** Forward amount to the new NFT item (covers gas + small balance). */
  forwardAmount: BN;
}): Promise<{ transferHash: string; seqno: number }> {
  const { contract, keyPair } = await getMintKeyWallet();
  const client = getClient();

  const seqno = await contract.getSeqNo();

  const internalMessage = new InternalMessage({
    to: args.collectionAddress,
    value: args.forwardAmount,
    bounce: true,
    body: new CommonMessageInfo({ body: new CellMessage(args.mintBody) }),
  });

  const transfer = contract.createTransfer({
    seqno,
    sendMode: 3, // pay fee separately + ignore errors when source has insufficient funds
    order: internalMessage,
    secretKey: keyPair.secretKey,
  });

  await client.sendExternalMessage(contract, transfer);

  return {
    transferHash: transfer.hash().toString("hex"),
    seqno,
  };
}
